# KNN from Scratch

Using the KNN algorithm from scikit-learn is quite simple. When you use it, you don't even need to know how KNN works and classifies the data points. The goal should be to really understand what you are doing. This is the only way to make sure you understand when something doesn't go the way you expect or want it to. Many people remember things best when they implement them themselves. So, let's build our own K-Nearest-Neighbors classifier!

**The purpose of this notebook is to help you remember the steps necessary to classify samples with KNN.**

To test if your code works, you can use the Iris dataset as a data example.
Let's make a plan and break this big task into smaller steps!


1. What information and data does the algorithm need to train and predict the classes of new instances?
This will be the input for our function! 

2. calculate the distance between the test point and each existing data point in the training data.
3. determine the nearest k neighbors.
4. make predictions based on these neighbors.

You have already implemented a function to calculate the distance between points, which will now come in handy.

A good way to get started, is to ignore the syntax and just write in simple text what you want your program to do aka **write pseudo-code**. You can then start to build out some of the structure. What variables are you going to need? What kinds of logic? 
Knowing where you’re going can help you make fewer mistakes as you’re trying to get there.

Note that for large data sets, the algorithm can take very long to classify because it has to calculate the distance between the test point and every other point in the data!

You can check if your pseudo-code contains all necessary steps afterwards, when scrolling down to "KNN algorithm from scratch" where you find an example of a knn pseudo-code.

## Import and Setup

In [ ]:
import numpy as np
import pandas as pd
from scipy.spatial import distance
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# Load data
df = pd.read_csv("data/iris.csv")

In [ ]:
# Defining X and y

In [ ]:
# Train test split


## Distance Metrics

As already explained, KNN assigns a class to the test point based on the majority class of  K  nearest neighbors. In general, euclidean distance is used to find nearest neighbors, but other distance metrics can also be used.

As the dimensionality of the feature space increases, the euclidean distance often becomes problematic due to the curse of dimensionality (discussed later).

In such cases, alternative vector-based similarity measures (dot product, cosine similarity, etc) are used to find the nearest neighbors. This transforms the original metric space into one more amenable to point-to-point measurements.

Another distance measure that you might consider is [Mahalanobis distance](https://en.wikipedia.org/wiki/Mahalanobis_distance). Mahalanobis distance attempts to weight features according to their probabilities. On some data sets that may be important.

In general, it's probably a good idea to normalize the data at a minimum. Here's a link to the scikit-learn scaling package: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html . You have to be a little circumspect about employing any technique where the answers change with scaling.

In [ ]:
# Implemented own distance function


## KNN Algorithm from scratch


Remember the steps:

1. What information and data does the algorithm need to train and predict the classes of new instances?
This will be the input for our function! 

2. calculate the distance between the test point and each existing data point in the training data.
3. determine the nearest k neighbors.
4. make predictions based on these neighbors.

Hopefully you have already thought of your gameplan, also called pseudo-code. If so, you can compare it to this one:
```
INPUT: X_train, y_train, X_test, k
FOR each object_to_predict in X_test:
    FOR each training_point, index in X_train:
        calculate distance d between object_to_predict and training_point
        store d and index
    SORT distances d in increasing order
    take first k items, get indices of those
    calculate most common class of points at indices in y_train (prediction)
    store prediction
RETURN list of predictions
````

Time to code!
Don't forget that it's good practice to document your own code! This way you can later understand what the purpose of each step was.
Maybe you can even use your pseudo code as documentation :)

In [1]:
# Your code
import numpy as np
from collections import Counter

def euclidean_distance(x1, x2):
    """
    Compute the Euclidean distance between two points.
    """
    return np.sqrt(np.sum((x1 - x2) ** 2))


def knn_predict(X_train, y_train, X_test, k=3):
    """
    Perform K-Nearest Neighbors classification.

    Parameters:
    - X_train: training feature data (numpy array)
    - y_train: training labels
    - X_test: test feature data
    - k: number of neighbors

    Returns:
    - predictions: list of predicted labels
    """
    
    predictions = []

    # Loop over each test point
    for test_point in X_test:
        
        distances = []

        # Compute distance to every training point
        for i, train_point in enumerate(X_train):
            d = euclidean_distance(test_point, train_point)
            distances.append((d, i))  # store distance + index

        # Sort distances (smallest first)
        distances.sort(key=lambda x: x[0])

        # Get indices of k nearest neighbors
        k_indices = [index for (_, index) in distances[:k]]

        # Get labels of k nearest neighbors
        k_labels = [y_train[i] for i in k_indices]

        # Majority vote
        most_common = Counter(k_labels).most_common(1)
        prediction = most_common[0][0]

        predictions.append(prediction)

    return predictions

## Comparison with sklearn knn implementation

That will be interesting! Check out how your implementation performs in comparison to the one of sklearn!
You can check the confusion matrix and the accuracy score of both algorithms.
If you want, you can check which algorithm is faster!

In [13]:
# Custom KNN
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
y_pred_custom = knn_predict(X_train, y_train, X_test, k=5)

# Sklearn KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_sklearn = knn.predict(X_test)


acc_custom = accuracy_score(y_test, y_pred_custom)
acc_sklearn = accuracy_score(y_test, y_pred_sklearn)

print("Custom KNN Accuracy:", acc_custom)
print("Sklearn KNN Accuracy:", acc_sklearn)
from sklearn.metrics import confusion_matrix

cm_custom = confusion_matrix(y_test, y_pred_custom)
cm_sklearn = confusion_matrix(y_test, y_pred_sklearn)

print("Custom KNN Confusion Matrix:\n", cm_custom)
print("\nSklearn KNN Confusion Matrix:\n", cm_sklearn)

Custom KNN Accuracy: 1.0
Sklearn KNN Accuracy: 1.0
Custom KNN Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Sklearn KNN Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [14]:
import time

# Custom KNN timing
start = time.time()
knn_predict(X_train, y_train, X_test, k=5)
end = time.time()
print("Custom KNN Time:", end - start)

# Sklearn KNN timing
start = time.time()
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn.predict(X_test)
end = time.time()
print("Sklearn KNN Time:", end - start)

Custom KNN Time: 0.08219003677368164
Sklearn KNN Time: 0.04098701477050781


sklearn’s implementation is significantly faster due to optimized numerical operations and efficient data structures. This demonstrates the importance of using optimized libraries in practical machine learning tasks.”